<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\BookAttachCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/BookAttachCommand.php';

$this->privates['App\\Command\\BookAttachCommand'] = $instance = new \App\Command\BookAttachCommand();

$instance->setName('book:attach');

return $instance;
