<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEYP64nR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEYP64nR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEYP64nR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEYP64nR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEYP64nR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EYP64nR',
    'container.build_id' => '1413bfa6',
    'container.build_time' => 1564702027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEYP64nR');
